config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  root "insta_clones#index"
  resources :sessions, only: [:new,:create,:destroy]
  resources :users, only: [:index,:new,:create,:update,:show,:destroy]
  resources :relationships, only: [:create,:destroy]
  resources :insta_clones, only: [:index]
  resources :favorites,only:[:create,:destroy]
  resources :blogs do
    collection do
      post :confirm
      get  :list
    end
    resources :comments
  end

  resources :conversations do
    resources :messages
  end

  mount LetterOpenerWeb::Engine,at:"/letter_opener" if Rails.env.development?
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :favorite_users,through: :favorites,source: :user
  has_many :comments,dependent: :destroy
  mount_uploader :image,ImageUploader
  validates :content_or_image,presence: true

  private

  def content_or_image
    content.presence or image.presence
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog,only: [:update,:show,:destroy]
  before_action :set_user_blog,only: [:create,:confirm]

  def list
    @blogs = Blog.all
  end

  def create
    if @blog.save
      BlogCreateMailer.blog_create_mail(@blog).deliver
      redirect_to root_path, notice: "ブログを作成しました"
    end
  end

  def update
    # binding.pry
    if @blog.user.id != current_user.id
      different_account
    elsif @blog.update(blog_params)
      redirect_to root_path, notice: "ブログを編集しました"
    else
      set_blog
      @blogs = Blog.all
      flash.now[:danger] = 'ブログ編集に失敗しました'
      render template: 'insta_clones/index'
    end
  end

  def confirm
    if @blog.invalid?
      @blogs = Blog.all
      favorite = current_user.favorites
      @blogs_favo = Blog.where(id: favorite.select("blog_id"))
      flash.now[:danger] = 'ブログ作成に失敗しました'
      render template: 'insta_clones/index'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    @comments = @blog.comments
    @comment = @blog.comments.build
  end

  def destroy
    @blog.destroy
    redirect_to root_path,notice: "ブログを削除しました"
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def set_user_blog
    @blog = current_user.blogs.build(blog_params)
  end

  def blog_params
    params.require(:blog).permit(:content,:image,:image_cache)
  end

  def different_account
    flash[:danger] = '不正なアクセスを検知しました'
    @blogs = Blog.all
    @blog = Blog.new
    favorite = current_user.favorites
    @blogs_favo = Blog.where(id: favorite.select("blog_id"))
    render template: 'insta_clones/index'
  end

end

app/views/blogs/confirm.html.erb
<div class="container-fluid">
  <div class="main_contents">
    <ul class="row row-eq-height">
      <li class="col-xs-12 col-sm-12 col-md-12 b-radius main_contents_area main_contents_background_color">
        <ul class="row row-eq-height">
          <li class="col-xs-12 col-sm-12 col-md-12 b-radius login_form ">
            <h1>確認画面</h1>
            <%= form_with(model: @blog,local: true) do |form| %>
              <table>
                <tr>
                  <td>投稿コメント：</td>
                  <td><%= @blog.content %></td>
                </tr>
                <tr>
                  <td>投稿写真：</td>
                  <td>
                    <% if @blog.image && @blog.image.url %>
                      <%= image_tag(@blog.image.url) %>
                    <% else %>
                      <%= image_tag('no_image.png') %>
                    <% end %>
                  </td>
                </tr>
              </table>
              <table>
                <tr>
                  <td><%= form.submit "投稿する",class: "btn btn-primary" %></td>
                  <%= form.hidden_field :content %>
                  <%= form.hidden_field :image_cache %>
            <% end %>

                  <%= form_with(model: @blog, url: root_path, local: true, method: 'get') do |form| %>
                    <td><%= form.submit "書き直す",name: 'back',class: "btn btn-info" %></td>
                    <td><%= link_to 'キャンセル',root_path ,class: "btn btn-danger" %></td>
                    <%= form.hidden_field :content %>
                    <%= form.hidden_field :image_cache %>
                  <% end %>
                </tr>
              </table>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/blogs/list.html.erb
<div class="container-fluid">
  <div class="b-radius main_contents_background_color">
  <h2 class="white">ALLブログ一覧</h2>
    <div class="row all_blog_list_menu">
      <% i = 0 %>
      <% @blogs.reverse().each do |list| %>
        <div class="col-md-4">
          <div class="card row no-gutters b-radius">
            <div class="col-xs-4 col-sm-4 col-md-4 card-img-top">
              <% if list.image && list.image.url %>
                <%= image_tag(list.image.url) %>
              <% else %>
                <%= image_tag('no_image.png') %>
              <% end %>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8">
              <div class="card-body">
                <h3 class="card-title">投稿したユーザー：<%= list.user.name %></h3>
                <p>コメント：<%= list.content %></p>
                <%= link_to '記事を見る',blog_path(id: list.id),class: "btn btn-primary btn-sm" %>
              </div>
            </div>
          </div>
        </div>
        <% i += 1 %>
        <% if i > 2 %>
          </div>
          <div class="row all_blog_list_menu">
          <% i = 0 %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="container-fluid main_contents">
  <ul class="row row-eq-height">
    <li class="col-xs-12 col-sm-12 col-md-12 b-radius main_contents_area main_contents_background_color">
      <ul class="row row-eq-height">
        <li class="col-xs-12 col-sm-12 col-md-12 b-radius login_form ">

          <h2>ブログ記事詳細ページ</h2>
          <p>
            投稿したユーザー：<%= @blog.user.name %>
            <%= link_to 'ユーザーのページへ',user_path(@blog.user.id) %>
          </p>
          <p>
            <% if @blog.image && @blog.image.url %>
              <%= image_tag(@blog.image.url) %>
            <% else %>
              <%= image_tag('no_image.png') %>
            <% end %>
          </p>
          <p>コメント：<%= @blog.content %></p>
          <% if current_user.name == @blog.user.name %>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@blog">編集</button>
            <%= link_to '削除',blog_path(id: @blog.id),method: :delete,class: "btn btn-danger" ,
                      data: {confirm: '本当に削除してもよろしいですか？',cancel: 'キャンセル',commit: '削除する',title: '削除確認'} %>
          <% end %>

          <% unless @blog.user_id == current_user.id %>
            <% if @favorite.present? %>
              <%= link_to 'お気に入り解除する',favorite_path(id: @favorite.id),method: :delete,class: 'btn btn-danger' %>
            <% else %>
              <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
            <% end %>
          <% end %>
          <%= link_to 'TOPページに戻る',root_path ,class: "btn btn-info" %>

          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">編集内容</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <%= form_with(model: @blog, local: true) do |form| %>
                  <div class="modal-body">
                      <div class="field">
                        <table>
                          <tr>
                            <th>コメント</th><td>：</td><td><%= form.text_area :content %></td>
                          </tr>
                          <tr>
                            <th>画像</th><td>：</td>
                            <td>
                              <div class="field image">
                                <%= form.label '↓クリックでファイル選択' %>
                                <div id="img_field" onClick="$('#file').click()">
                                  <% if @blog.image.url.present? %>
                                    <%= image_tag(@blog.image.url,:size => "200x150") %>
                                  <% else %>
                                    <i><%= fa_icon("image") %></i><i class="add"><%= fa_icon("upload") %></i>
                                  <% end %>
                                </div>
                              </div>
                            </td>
                          </tr>
                        </table>
                        <br>
                        <p>画像を変更したい場合は、新しい画像を選択して下さい</p>
                        <%= form.file_field :image,class: "image", style: "display:none;",id: "file" %>
                        <%= form.hidden_field @blog.image.url if @blog.image && @blog.image.url %>
                      </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                    <input type="reset" value="リセット" class="btn btn-secondary" id="deleteButton" onclick="img_field_change()">
                      <%= form.submit("確定",class: "btn btn-primary",
                                      data:{confirm: '本当に編集してもよろしいですか？',cancel: 'キャンセル',commit: '編集する',title: '編集確認'}) %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <script>
            const img_field_change = function(){
              const img_chenge = document.getElementById('img_field');
              <% if @blog.image && @blog.image.url %>
                img_chenge.innerHTML = '<%= image_tag(@blog.image.url,:size => "200x150") %>';
              <% else %>
                img_chenge.innerHTML = '<i><%= fa_icon("image") %></i><i class="add"><%= fa_icon("upload") %></i>';
              <% end %>
            }
          </script>

        </li>
      </ul>
    </li>
  </ul>
</div>

<!-- Ajax勉強　ブログ記事にコメント機能搭載 -->
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="blog-text">
    <h2>ブログ記事詳細ページ</h2>
      <p>
        投稿したユーザー：<%= @blog.user.name %>
        <%= link_to 'ユーザーのページへ',user_path(@blog.user.id) %>
      </p>
      <p>
        <% if @blog.image && @blog.image.url %>
          <%= image_tag(@blog.image.url) %>
        <% else %>
          <%= image_tag('no_image.png') %>
        <% end %>
      </p>
      <p>コメント：<%= @blog.content %></p>
  </div>

  <p>コメント一覧(ここから下の内容が重要)</p>
  <!-- comments_areaというHTMLのidを取得して、そのdivの部分だけを更新する -->
  <div id="comments_area">
    <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
    <%= render partial: 'comments/index',locals: { comments: @comments , blog: @blog } %>
  </div>
  <!-- コメント入力欄をblog/showページに表示するためのrender -->
  <%= render partial: 'comments/form',locals: { comment: @comment,blog: @blog} %>

</div>

app/views/blogs/test.html.erb
<div class="container-fluid main_contents">
  <ul class="row row-eq-height">
    <li class="col-xs-12 col-sm-12 col-md-12 b-radius main_contents_area main_contents_background_color">
      <ul class="row row-eq-height">
        <li class="col-xs-12 col-sm-12 col-md-12 b-radius login_form ">

          <h2>ブログ記事詳細ページ</h2>
          <p>投稿したユーザー：<%= @blog.user.name %></p>
          <p>
            <% if @blog.image && @blog.image.url %>
              <%= image_tag(@blog.image.url) %>
            <% else %>
              <%= image_tag('no_image.png') %>
            <% end %>
          </p>
          <p>コメント：<%= @blog.content %></p>
          <% if current_user.name == @blog.user.name %>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@blog">編集</button>
            <%= link_to '削除',blog_path(id: @blog.id),method: :delete,class: "btn btn-danger" ,
                      data: {confirm: '本当に削除してもよろしいですか？',cancel: 'キャンセル',commit: '削除する',title: '削除確認'} %>
          <% end %>
          <% unless @blog.user_id == current_user.id %>
            <% if @favorite.present? %>
              <%= link_to 'お気に入り解除する',favorite_path(id: @favorite.id),method: :delete,class: 'btn btn-danger' %>
            <% else %>
              <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
            <% end %>
          <% end %>
          <%= link_to 'TOPページに戻る',root_path ,class: "btn btn-info" %>

          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">編集内容</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <%= form_with(model: @blog, local: true) do |form| %>
                  <div class="modal-body">
                      <div class="field">
                        <table>
                          <tr>
                            <th>コメント</th><td>：</td><td><%= form.text_area :content %></td>
                          </tr>
                          <tr>
                            <th>画像</th><td>：</td>
                            <td>
                              <div class="field image">
                                <%= form.label '↓クリックでファイル選択' %>
                                <div id="img_field" onClick="$('#file').click()">
                                  <% if @blog.image.url.present? %>
                                    <%= image_tag(@blog.image.url,:size => "200x150") %>
                                  <% else %>
                                    <i><%= fa_icon("image") %></i><i class="add"><%= fa_icon("upload") %></i>
                                  <% end %>
                                </div>
                              </div>
                            </td>
                          </tr>
                        </table>
                        <br>
                        <p>画像を変更したい場合は、新しい画像を選択して下さい</p>
                        <%= form.file_field :image,class: "image", style: "display:none;",id: "file" %>
                        <%= form.hidden_field @blog.image.url if @blog.image && @blog.image.url %>
                      </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                    <input type="reset" value="リセット" class="btn btn-secondary" id="deleteButton" onclick="img_field_change()">
                      <%= form.submit("確定",class: "btn btn-primary",
                                      data:{confirm: '本当に編集してもよろしいですか？',cancel: 'キャンセル',commit: '編集する',title: '編集確認'}) %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <script>
            const img_field_change = function(){
              const img_chenge = document.getElementById('img_field');
              <% if @blog.image && @blog.image.url %>
                img_chenge.innerHTML = '<%= image_tag(@blog.image.url,:size => "200x150") %>';
              <% else %>
                img_chenge.innerHTML = '<i><%= fa_icon("image") %></i><i class="add"><%= fa_icon("upload") %></i>';
              <% end %>
            }
          </script>

        </li>
      </ul>
    </li>
  </ul>
</div>