config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  root "insta_clones#index"
  resources :sessions, only: [:new,:create,:destroy]
  resources :users, only: [:index,:new,:create,:update,:show,:destroy]
  resources :relationships, only: [:create,:destroy]
  resources :insta_clones, only: [:index]
  resources :favorites,only:[:create,:destroy]
  resources :blogs do
    collection do
      post :confirm
      get  :list
    end
    resources :comments
  end

  resources :conversations do
    resources :messages
  end

  mount LetterOpenerWeb::Engine,at:"/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :favorites,dependent: :destroy

  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name , presence: true, length: { maximum:30  }
  validates :email, presence: true, length: { maximum:255 }, uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true,length: { minimum: 6 }, unless: :password_digest
  mount_uploader :image, ImageUploader

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only:[:show,:update,:destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserAccountCreateMailer.user_account_create_mail(@user).deliver
      flash[:notice] = 'アカウント作成に成功しました'
      redirect_to root_path
    else
      @blog = Blog.new
      render template: 'insta_clones/index'
    end
  end

  def update
    # binding.pry
    if @user.id != current_user.id
      different_account
    elsif @user.update(user_params)
      redirect_to user_path(current_user.id), notice: "プロフィール画像を更新しました"
    else
      redirect_to user_path(current_user.id), notice: 'プロフィール画像の更新に失敗しました'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path,notice: "ブログを削除しました"
  end

  def show
    favorite = current_user.favorites
    @blogs_favo = Blog.where(id: favorite.select("blog_id"))
    @my_blogs = Blog.where(user_id: @user.id)
    user = User.find_by(id: params[:id])
    @following = user.following
    @followers = user.followers
    binding.pry
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:image,:image_cache)
  end

  def different_account
    flash[:danger] = '不正なアクセスを検知しました'
    @blogs = Blog.all
    @blog = Blog.new
    favorite = current_user.favorites
    @blogs_favo = Blog.where(id: favorite.select("blog_id"))
    render template: 'insta_clones/index'
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id),method: :delete) do |f| %>
      <%= f.submit "フォロー解除する" %>
    <% end %>
  <% end %>

</div>

app/views/users/index.html.erb
<h1>ユーザー</h1>
<% @users.each do |user| %>
  <%= user.name %>
  <%= user.email %>
  <%= render 'follow_form',user: user %>
<% end %>

<% @users.each do |user| %>
  <% if user.id != current_user.id %>
    <li>
      <div class="item">
        <%= link_to user.name, user %>
        <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
      </div>
    </li>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid">
  <ul class="row accordion">
    <li class="col-xs-12 col-sm-12 col-md-12 center alert alert-danger" role="alert">
      <% flash.each do |key,value| %>
        <%= content_tag(:div,value,class: "#{key}") %>
      <% end %>
    </li>
  </ul>
  <div class="b-radius main_contents_background_color">
    <ul class="row accordion">
      <li class="hidden-xs hidden-sm col-md-12 b-radius main_contents_area main_contents_background_color">
        <div class="row profile_background b-radius user_center">
          <p><h2><%= @user.name %>さんのアカウント詳細ページ</h2></p>
          <p>メールアドレス： <%= @user.email %></p>
          <!-- アイコンを設定していなければNoUserImageを表示。設定していたらアップロードした画像を表示-->
          <% if @user.image && @user.image.url %>
            <%= image_tag(@user.image.url,size: "200x150") %>
          <% else %>
            <i class="far fa-user menu_right user_icon"></i>
          <p>No image</p>
          <% end %>

          <br>

          <% if current_user.id == @user.id %>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@blog">編集</button>
            <!--
              <%= link_to '削除',user_path(id: @user.id),method: :delete,class: "btn btn-danger" ,
                      data: {confirm: '本当に削除してもよろしいですか？',cancel: 'キャンセル',commit: '削除する',title: '削除確認'} %>
            -->
          <% end %>
        </div>
      </li>
    </ul>

    <ul class="row all_blog_list_menu">
      <li class="col-xs-12 col-sm-12 col-md-12">
        <div class="row b-radius favo_h">
          <h4><%= @user.name %>さんが、投稿したブログ一覧</h4>
        </div>
      </li>
    </ul>

    <div class="row all_blog_list_menu">
      <% i = 0 %>
      <% @my_blogs.reverse().each do |list| %>
        <div class="col-md-4">
          <div class="card row no-gutters b-radius">
            <div class="col-xs-4 col-sm-4 col-md-4 card-img-top">
              <% if list.image && list.image.url %>
                <%= image_tag(list.image.url) %>
              <% else %>
                <%= image_tag('no_image.png') %>
              <% end %>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8">
              <div class="card-body">
                <h3 class="card-title">投稿したユーザー：<%= list.user.name %></h3>
                <p>コメント：<%= list.content %></p>
                <%= link_to '記事を見る',blog_path(id: list.id),class: "btn btn-primary btn-sm" %>
              </div>
            </div>
          </div>
        </div>
        <% i += 1 %>
        <% if i > 2 %>
          </div>
          <div class="row all_blog_list_menu">
            <% i = 0 %>
        <% end %>
      <% end %>
    </div>


    <ul class="row all_blog_list_menu">
      <li class="col-xs-12 col-sm-12 col-md-12">
        <div class="row b-radius favo_h">
          <h4><%= @user.name %>さんが、お気に入り登録したブログ一覧</h4>
        </div>
      </li>
    </ul>

    <div class="row all_blog_list_menu">
      <% i = 0 %>
      <% @blogs_favo.reverse().each do |list| %>
        <div class="col-md-4">
          <div class="card row no-gutters b-radius">
            <div class="col-xs-4 col-sm-4 col-md-4 card-img-top">
              <% if list.image && list.image.url %>
                <%= image_tag(list.image.url) %>
              <% else %>
                <%= image_tag('no_image.png') %>
              <% end %>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8">
              <div class="card-body">
                <h3 class="card-title">投稿したユーザー：<%= list.user.name %></h3>
                <p>コメント：<%= list.content %></p>
                <%= link_to '記事を見る',blog_path(id: list.id),class: "btn btn-primary btn-sm" %>
              </div>
            </div>
          </div>
        </div>
        <% i += 1 %>
        <% if i > 2 %>
          </div>
          <div class="row all_blog_list_menu">
            <% i = 0 %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<h3>フォローしている人</h3>
<% @following.each do |following| %>
  <%= following.name %><br>
<% end %>

<h3>フォローされている人</h3>
<% @followers.each do |followers| %>
  <%= followers.name %><br>
<% end %>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">編集内容</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with(model: @user, local: true) do |form| %>
        <div class="modal-body">
            <div class="field">
              <table>
                <tr>
                  <td>e-mail</td><td>：</td><td><%= form.text_area :email %></td>
                </tr>
                <tr>
                  <th>画像</th><td>：</td>
                  <td>
                    <div class="field image">
                      <%= form.label '↓クリックでファイル選択' %>
                      <div id="img_field" onClick="$('#file').click()">
                        <% if @user.image.present? %>
                          <%= image_tag(@user.image.url,:size => "200x150") %>
                        <% else %>
                          <i><%= fa_icon("image") %></i><i class="add"><%= fa_icon("upload") %></i>
                        <% end %>
                      </div>
                    </div>
                  </td>
                </tr>
              </table>

              <br>
              <p>画像を変更したい場合は、新しい画像を選択して下さい</p>
              <%= form.file_field :image,class: "image", style: "display:none;",id: "file" %>
              <%= form.hidden_field @user.image.url if @user.image && @user.image.url %>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <input type="reset" value="リセット" class="btn btn-secondary" id="deleteButton" onclick="img_field_change()">
            <%= form.submit("確定",class: "btn btn-primary",
                            data:{confirm: '本当に編集してもよろしいですか？',cancel: 'キャンセル',commit: '編集する',title: '編集確認'}) %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<script>
  const img_field_change = function(){
    const img_chenge = document.getElementById('img_field');
    <% if @user.image && @user.image.url %>
      img_chenge.innerHTML = '<%= image_tag(@user.image.url,:size => "200x150") %>';
    <% else %>
      img_chenge.innerHTML = '<i><%= fa_icon("image") %></i><i class="add"><%= fa_icon("upload") %></i>';
    <% end %>
  }
</script>