config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  root "insta_clones#index"
  resources :sessions, only: [:new,:create,:destroy]
  resources :users, only: [:index,:new,:create,:update,:show,:destroy]
  resources :relationships, only: [:create,:destroy]
  resources :insta_clones, only: [:index]
  resources :favorites,only:[:create,:destroy]
  resources :blogs do
    collection do
      post :confirm
      get  :list
    end
    resources :comments
  end

  resources :conversations do
    resources :messages
  end

  mount LetterOpenerWeb::Engine,at:"/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :favorite_users,through: :favorites,source: :user
  has_many :comments,dependent: :destroy
  mount_uploader :image,ImageUploader
  validates :content_or_image,presence: true

  private

  def content_or_image
    content.presence or image.presence
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  #会話はUserの概念をsenderとrecipientに分けた形でアソシエーションする
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
  # １つの会話はメセージをたくさん含む 一対多。会話履歴がなくなれば、それに付随するメッセージ群も消える
  has_many :messages, dependent: :destroy

  # sender_idとrecipient_idが同じ組み合わせで保存されないようにする
  validates_uniqueness_of :sender_id, scope: :recipient_id
  
  # =?は存在していたらtrueを返す。
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end

  # 会話の相手の情報を取得する
  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
    binding.pry
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
  # m=月,d=日,y=西暦下二桁 l=12時間制の時,M=分,p=AM/PM
  def message_time
    # strftime( at )は何をしている？後でrails cやbinding.pryで確認
    created_at.strftime("%m/%d/%y at %l:%M %p")
    # binding.pry
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title,presence: true, uniqueness: true,length:{ maximum:100 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :favorites,dependent: :destroy

  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name , presence: true, length: { maximum:30  }
  validates :email, presence: true, length: { maximum:255 }, uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true,length: { minimum: 6 }, unless: :password_digest
  mount_uploader :image, ImageUploader

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog,only: [:update,:show,:destroy]
  before_action :set_user_blog,only: [:create,:confirm]

  def list
    @blogs = Blog.all
  end

  def create
    if @blog.save
      BlogCreateMailer.blog_create_mail(@blog).deliver
      redirect_to root_path, notice: "ブログを作成しました"
    end
  end

  def update
    # binding.pry
    if @blog.user.id != current_user.id
      different_account
    elsif @blog.update(blog_params)
      redirect_to root_path, notice: "ブログを編集しました"
    else
      set_blog
      @blogs = Blog.all
      flash.now[:danger] = 'ブログ編集に失敗しました'
      render template: 'insta_clones/index'
    end
  end

  def confirm
    if @blog.invalid?
      @blogs = Blog.all
      favorite = current_user.favorites
      @blogs_favo = Blog.where(id: favorite.select("blog_id"))
      flash.now[:danger] = 'ブログ作成に失敗しました'
      render template: 'insta_clones/index'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    @comments = @blog.comments
    @comment = @blog.comments.build
  end

  def destroy
    @blog.destroy
    redirect_to root_path,notice: "ブログを削除しました"
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def set_user_blog
    @blog = current_user.blogs.build(blog_params)
  end

  def blog_params
    params.require(:blog).permit(:content,:image,:image_cache)
  end

  def different_account
    flash[:danger] = '不正なアクセスを検知しました'
    @blogs = Blog.all
    @blog = Blog.new
    favorite = current_user.favorites
    @blogs_favo = Blog.where(id: favorite.select("blog_id"))
    render template: 'insta_clones/index'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only:[:show,:update,:destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserAccountCreateMailer.user_account_create_mail(@user).deliver
      flash[:notice] = 'アカウント作成に成功しました'
      redirect_to root_path
    else
      @blog = Blog.new
      render template: 'insta_clones/index'
    end
  end

  def update
    # binding.pry
    if @user.id != current_user.id
      different_account
    elsif @user.update(user_params)
      redirect_to user_path(current_user.id), notice: "プロフィール画像を更新しました"
    else
      redirect_to user_path(current_user.id), notice: 'プロフィール画像の更新に失敗しました'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path,notice: "ブログを削除しました"
  end

  def show
    favorite = current_user.favorites
    @blogs_favo = Blog.where(id: favorite.select("blog_id"))
    @my_blogs = Blog.where(user_id: @user.id)
    user = User.find_by(id: params[:id])
    @following = user.following
    @followers = user.followers
    binding.pry
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:image,:image_cache)
  end

  def different_account
    flash[:danger] = '不正なアクセスを検知しました'
    @blogs = Blog.all
    @blog = Blog.new
    favorite = current_user.favorites
    @blogs_favo = Blog.where(id: favorite.select("blog_id"))
    render template: 'insta_clones/index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/insta_clones_helper.rb
module InstaClonesHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>instagram_clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>

    <div class="container-field">
      <header>
        <nav>
          <ul class="row menu">
            <li class="col-xs-2 col-sm-2 col-md-7 menu_top_link"><i class="fab fa-instagram"></i>｜instagram_clone</li>
            <li class="col-xs-2 col-sm-2 col-md-1 center"><a href="https://github.com/noriya1217/insta_clone">GitHub</a></li>
            <% if logged_in? %>
              <%# <li class="hidden-xs hidden-sm col-md-3">検索ボックス</li> %>
              <li class="col-xs-2 col-sm-2 col-md-1 center"><%= link_to "ホーム", insta_clones_path %></li>
              <li class="col-xs-2 col-sm-2 col-md-1 center"><%= link_to "Profile", user_path(current_user.id) %></li>
              <li class="col-xs-2 col-sm-2 col-md-1 center"><%= link_to "UserList", users_path if logged_in? %></li>
              <li class="col-xs-2 col-sm-2 col-md-1 center"><%= link_to "Logout" , session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li class="col-xs-6 col-sm-6 col-md-6"></li>
            <% end %>
          </ul>
        </nav>
      </header>
    </div>

    <%= yield %>

    <div class="container-field footer_container">
      <footer>
        <nav>
          <ul class="row">
            <li class="col-xs-12 col-sm-12 col-md-12 center">
              <p>
                <b><a href="#" class="footer_link">INSTAGRAMについて</a></b>
                <b><a href="#" class="footer_link">サポート</a></b>
                <b><a href="#" class="footer_link">プレス</a></b>
                <b><a href="#" class="footer_link">API</a></b>
                <b><a href="#" class="footer_link">求人</a></b>
                <b><a href="#" class="footer_link">プライバシー</a></b>
                <b><a href="#" class="footer_link">利用規約</a></b>
                <b><a href="#" class="footer_link">ディレクトリ</a></b>
                <b><a href="#" class="footer_link">プロフィール</a></b>
                <b><a href="#" class="footer_link">ハッシュタグ</a></b>
                <b><a href="#" class="footer_link">言語</a></b>
                <b class="copyright">©2019 INSTAGRAM CLONE</b>
              </p>
            </li>
          </ul>
        </nav>
      </footer>

  </body>
</html>